### ISSUE TITLE
delete / overwrite

### ISSUE THREAD

**Issue by flurischt** [flurischt/image_resize_service#12]
make sure to delete all resize in the storage when the original image is deleted or overwritten. 
example:
there's an image with two sizes, orig and small.
now orig is overwritten with another image. 
IS: small will always serve the old image
SHOULD: small should be a smaller version of the new image...

**Comment by webair** [comment]
Wie rufe ich die swagger api docs auf?

**Comment by flurischt** [comment]
link stand früher im "index. html"  template. Kannst du in der git history
nachschauen?

**Comment by flurischt** [comment]
steht sogar im readme: /api/spec.html#!/spec.json
