### ISSUE TITLE
Pfad angeben

### ISSUE THREAD

**Issue by webair** [flurischt/image_resize_service#8]
Wäre noch gut, wenn man Pfäde angeben könnte, so könnte man Namenskonflikte umgehen.

**Comment by flurischt** [comment]
sice your refactoring put anyway. implement if you need it or close the ticket. ;)

**Comment by webair** [comment]
Ist eigentlich so implementier:

POST <project>/ -> Bild wird erstellt, wenn name schon exisitert wird -1 angehängt. 
PUT <project>/<image_name> -> Bild wird erstellt oder aktualisiert (inkl. löschen der thunbs)
